quartz.jobStore.type = Quartz.Impl.AdoJobStore.JobStoreTX, Quartz
quartz.jobStore.driverDelegateType = Quartz.Impl.AdoJobStore.StdAdoDelegate, Quartz
quartz.jobStore.tablePrefix = QRTZ_
quartz.jobStore.dataSource = myDS

quartz.dataSource.myDS.connectionString = Data Source=d:\quartz.db3;Version=3;
quartz.dataSource.myDS.provider = SQLite-106

# Sqlite 1.0.105.1 + ADO Net provider for sqlite
# Driver can be found at : http://sqlite.phxsoftware.com
quartz.dbprovider.SQLite-106.assemblyName=System.Data.SQLite, Version=1.0.61.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139
quartz.dbprovider.SQLite-106.connectionType=System.Data.SQLite.SQLiteConnection, System.Data.SQLite, Version=1.0.105.1, Culture=neutral, PublicKeyToken=db937bc2d44ff139
quartz.dbprovider.SQLite-106.commandType=System.Data.SQLite.SQLiteCommand, System.Data.SQLite, Version=1.0.105.1, Culture=neutral, PublicKeyToken=db937bc2d44ff139
quartz.dbprovider.SQLite-106.parameterType=System.Data.SQLite.SQLiteParameter, System.Data.SQLite, Version=1.0.105.1, Culture=neutral, PublicKeyToken=db937bc2d44ff139
#quartz.dbprovider.SQLite-106.dataAdapterType=System.Data.SQLite.SQLiteDataAdapter , System.Data.SQLite, Version=1.0.105.1, Culture=neutral, PublicKeyToken=db937bc2d44ff139
quartz.dbprovider.SQLite-106.commandBuilderType=System.Data.SQLite.SQLiteCommandBuilder, System.Data.SQLite, Version=1.0.105.1, Culture=neutral, PublicKeyToken=db937bc2d44ff139
#quartz.dbprovider.SQLite-106.commandBuilderDeriveParametersMethod=DeriveParameters
quartz.dbprovider.SQLite-106.parameterDbType=System.Data.SQLite.TypeAffinity, System.Data.SQLite, Version=1.0.105.1, Culture=neutral, PublicKeyToken=db937bc2d44ff139
quartz.dbprovider.SQLite-106.parameterDbTypePropertyName=DbType
#quartz.dbprovider.SQLite-106.parameterIsNullableProperty=IsNullable
quartz.dbprovider.SQLite-106.parameterNamePrefix=@
quartz.dbprovider.SQLite-106.exceptionType=System.Data.SQLite.SQLiteException, System.Data.SQLite, Version=1.0.105.1, Culture=neutral, PublicKeyToken=db937bc2d44ff139
quartz.dbprovider.SQLite-106.useParameterNamePrefixInParameterCollection=true
quartz.dbprovider.SQLite-106.bindByName=true
