<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <UnityVersion>2020.2.0f1</UnityVersion>
    <LangVersion>latest</LangVersion>
    <Version>1.2.18</Version>
    <Deterministic>true</Deterministic>
    <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DeepMeta.$(AssemblyName)</PackageId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="AwaitHelper\**" />
    <Compile Remove="Impl\**" />
    <EmbeddedResource Remove="AwaitHelper\**" />
    <EmbeddedResource Remove="Impl\**" />
    <None Remove="AwaitHelper\**" />
    <None Remove="Impl\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="ResourceViewer\ResourceLoader.cs" />
    <Compile Remove="ResourceViewer\Text3D.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="UnityTechnologies.UnityEngine" Version="2020.2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeepCore.GUI\DeepCore.GUI.csproj" />
    <ProjectReference Include="..\DeepCore\DeepCore.csproj" />
  </ItemGroup>
</Project>