<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<UnityVersion>2020.2.0f1</UnityVersion>
		<LangVersion>latest</LangVersion>
		<Deterministic>true</Deterministic>
		<Configurations>Debug;Release;Source</Configurations>
	</PropertyGroup>
	
	<PropertyGroup>
	  <DefineConstants>$(DefineConstants);UNITY_5_4_OR_NEWER;UNITASK_UGUI_SUPPORT,UNITY_2017_1_OR_NEWER;UNITY_STANDALONE_WIN</DefineConstants>
	  <RootNamespace>DeepCore.Unity</RootNamespace>
	 
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <DefineConstants>$(DefineConstants);UNITASK_UGUI_SUPPORT,UNITY_2017_1_OR_NEWER;UNITY_5_4_OR_NEWER;FGUI;NATIVE_WEBSOCKET</DefineConstants>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DefineConstants>$(DefineConstants);UNITASK_UGUI_SUPPORT,UNITY_2017_1_OR_NEWER;UNITY_5_4_OR_NEWER;FGUI;NATIVE_WEBSOCKET</DefineConstants>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Source|AnyCPU'">
	  <DefineConstants>$(DefineConstants);UNITASK_UGUI_SUPPORT,UNITY_2017_1_OR_NEWER;UNITY_5_4_OR_NEWER;FGUI;NATIVE_WEBSOCKET</DefineConstants>
	</PropertyGroup>
	
	<ItemGroup>
	  <Compile Remove="Assets\Library\**" />
	  <Compile Remove="Assets\Plugins\DeepCore\Resource\**" />
	  <Compile Remove="Assets\Plugins\HudNum\**" />
	  <Compile Remove="Assets\Plugins\IngameDebugConsole\**" />
	  <Compile Remove="Assets\Plugins\Sirenix\**" />
	  <Compile Remove="Assets\Plugins\UniTask\**" />
	  <Compile Remove="FunctionCall\HudNum\**" />
	  <Compile Remove="FunctionCall\IngameDebugConsole\**" />
	  <Compile Remove="FunctionCall\NativeWebSocket-master\**" />
	  <Compile Remove="FunctionCall\Sirenix\**" />
	  <Compile Remove="FunctionCall\Spine\**" />
	  <Compile Remove="FunctionCall\UniTask\**" />
	  <Compile Remove="Library\**" />
	  <Compile Remove="Logs\**" />
	  <Compile Remove="Managed\**" />
	  <Compile Remove="Packages\**" />
	  <Compile Remove="ProjectSettings\**" />
	  <Compile Remove="UniTask\**" />
	  <Compile Remove="UserSettings\**" />
	  <EmbeddedResource Remove="Assets\Library\**" />
	  <EmbeddedResource Remove="Assets\Plugins\DeepCore\Resource\**" />
	  <EmbeddedResource Remove="Assets\Plugins\HudNum\**" />
	  <EmbeddedResource Remove="Assets\Plugins\IngameDebugConsole\**" />
	  <EmbeddedResource Remove="Assets\Plugins\Sirenix\**" />
	  <EmbeddedResource Remove="Assets\Plugins\UniTask\**" />
	  <EmbeddedResource Remove="FunctionCall\HudNum\**" />
	  <EmbeddedResource Remove="FunctionCall\IngameDebugConsole\**" />
	  <EmbeddedResource Remove="FunctionCall\NativeWebSocket-master\**" />
	  <EmbeddedResource Remove="FunctionCall\Sirenix\**" />
	  <EmbeddedResource Remove="FunctionCall\Spine\**" />
	  <EmbeddedResource Remove="FunctionCall\UniTask\**" />
	  <EmbeddedResource Remove="Library\**" />
	  <EmbeddedResource Remove="Logs\**" />
	  <EmbeddedResource Remove="Managed\**" />
	  <EmbeddedResource Remove="Packages\**" />
	  <EmbeddedResource Remove="ProjectSettings\**" />
	  <EmbeddedResource Remove="UniTask\**" />
	  <EmbeddedResource Remove="UserSettings\**" />
	  <None Remove="Assets\Library\**" />
	  <None Remove="Assets\Plugins\DeepCore\Resource\**" />
	  <None Remove="Assets\Plugins\HudNum\**" />
	  <None Remove="Assets\Plugins\IngameDebugConsole\**" />
	  <None Remove="Assets\Plugins\Sirenix\**" />
	  <None Remove="Assets\Plugins\UniTask\**" />
	  <None Remove="FunctionCall\HudNum\**" />
	  <None Remove="FunctionCall\IngameDebugConsole\**" />
	  <None Remove="FunctionCall\NativeWebSocket-master\**" />
	  <None Remove="FunctionCall\Sirenix\**" />
	  <None Remove="FunctionCall\Spine\**" />
	  <None Remove="FunctionCall\UniTask\**" />
	  <None Remove="Library\**" />
	  <None Remove="Logs\**" />
	  <None Remove="Managed\**" />
	  <None Remove="Packages\**" />
	  <None Remove="ProjectSettings\**" />
	  <None Remove="UniTask\**" />
	  <None Remove="UserSettings\**" />
	</ItemGroup>
	
	<ItemGroup>
	  <Compile Remove="Assets\Plugins\DeepCore\WebSocket\Connection.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DeepCore.Unity.GUI\DeepCore.Unity.GUI.csproj" />
		<ProjectReference Include="..\DeepCore.UnityEditor\DeepCore.UnityEditor.csproj" />
		<ProjectReference Include="..\DeepCore.Unity\DeepCore.Unity.csproj" />
		<ProjectReference Include="..\DeepCore\DeepCore.csproj" />
		<ProjectReference Include="..\DeepCore.Net\DeepCore.Net.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="UniTask" Version="2.5.10" />
		<PackageReference Include="UnityTechnologies.UnityEngine" Version="2020.2.2.1" />
	</ItemGroup>


	<ItemGroup>
		<EmbeddedResource Include="copydll.bat" />
		<EmbeddedResource Include="copydll.exclude.packages.txt" />
		<EmbeddedResource Include="copydll.exclude.txt" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copydll.bat $(TargetDir)" />
	</Target>



</Project>