<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <Version>1.2.17</Version>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DeepMeta.$(AssemblyName)</PackageId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants>TRACE;DEBUG;NETSTANDARD;NETSTANDARD2_0</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Cell\**" />
    <Compile Remove="Display\**" />
    <Compile Remove="Gemo\**" />
    <Compile Remove="Loader\**" />
    <Compile Remove="M3Z\**" />
    <Compile Remove="SceneGraph\**" />
    <Compile Remove="Sound\**" />
    <Compile Remove="Text\**" />
    <Compile Remove="Tool\**" />
    <EmbeddedResource Remove="Cell\**" />
    <EmbeddedResource Remove="Display\**" />
    <EmbeddedResource Remove="Gemo\**" />
    <EmbeddedResource Remove="Loader\**" />
    <EmbeddedResource Remove="M3Z\**" />
    <EmbeddedResource Remove="SceneGraph\**" />
    <EmbeddedResource Remove="Sound\**" />
    <EmbeddedResource Remove="Text\**" />
    <EmbeddedResource Remove="Tool\**" />
    <None Remove="Cell\**" />
    <None Remove="Display\**" />
    <None Remove="Gemo\**" />
    <None Remove="Loader\**" />
    <None Remove="M3Z\**" />
    <None Remove="SceneGraph\**" />
    <None Remove="Sound\**" />
    <None Remove="Text\**" />
    <None Remove="Tool\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Data\Color.cs" />
    <Compile Remove="UIFactory.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Cell\Constants.cs" />
    <Compile Include="Cell\CPJFileLoader.cs" />
    <Compile Include="Cell\CPJObject.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeepCore.Geometry\DeepCore.Geometry.csproj" />
    <ProjectReference Include="..\DeepCore\DeepCore.csproj" />
  </ItemGroup>
</Project>