<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <DefineConstants>ZIP_VOX</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.2.15</Version>
    <Deterministic>true</Deterministic>
    <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DeepMeta.$(AssemblyName)</PackageId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Extensions\Minecraft\**" />
    <Compile Remove="github\**" />
    <Compile Remove="StreamingVoxel\**" />
    <EmbeddedResource Remove="Extensions\Minecraft\**" />
    <EmbeddedResource Remove="github\**" />
    <EmbeddedResource Remove="StreamingVoxel\**" />
    <None Remove="Extensions\Minecraft\**" />
    <None Remove="github\**" />
    <None Remove="StreamingVoxel\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="VoxelWorld.SpaceDiv.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Data\VoxelWorld.SpaceDiv.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeepCore.Geometry\DeepCore.Geometry.csproj" />
    <ProjectReference Include="..\DeepCore\DeepCore.csproj" />
  </ItemGroup>
</Project>