<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.2.22</Version>
		<Deterministic>true</Deterministic>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
		<Configurations>Debug;Release;Source</Configurations>
		<AssemblyName>gamecli</AssemblyName>
		<StartupObject>Program</StartupObject>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<OutputPath>..\.outputs\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>DeepMeta.$(AssemblyName)</PackageId>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="TempProject\**" />
		<EmbeddedResource Remove="TempProject\**" />
		<None Remove="TempProject\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="init_project.bat" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="..\DeepCore.Console\Exec.cs" Link="Exec.cs" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="init_project.bat">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>


</Project>