<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <AssemblyName>svncombine</AssemblyName>
    <StartupObject>DeepTools.SvnCombiner.Program</StartupObject>
    <Version>1.2.14</Version>
    <Deterministic>true</Deterministic>
    <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DeepMeta.DeepTools.SvnCombiner</PackageId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="svncombine_filter.xml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="svncombine_filter.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeepCore\DeepCore.csproj" />
  </ItemGroup>
</Project>