//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepEditor.Common.EventEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class EventEditorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EventEditorSettings defaultInstance = ((EventEditorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EventEditorSettings())));
        
        public static EventEditorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 9pt")]
        public global::System.Drawing.Font EventFunctionFont {
            get {
                return ((global::System.Drawing.Font)(this["EventFunctionFont"]));
            }
            set {
                this["EventFunctionFont"] = value;
            }
        }
    }
}
