<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Version>1.2.19</Version>
    <RootNamespace>DeepCore.Game3D.Slave</RootNamespace>
    <Deterministic>true</Deterministic>
    <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DeepMeta.$(AssemblyName)</PackageId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Agent\**" />
    <Compile Remove="Client\**" />
    <Compile Remove="Replay\**" />
    <EmbeddedResource Remove="Agent\**" />
    <EmbeddedResource Remove="Client\**" />
    <EmbeddedResource Remove="Replay\**" />
    <None Remove="Agent\**" />
    <None Remove="Client\**" />
    <None Remove="Replay\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Layer\LayerSpell.cs" />
    <Compile Remove="Layer\Spell\LayerSpell.cs" />
    <Compile Remove="Layer\ZeroGravityFlyComponent.cs" />
    <Compile Remove="Runtime\NetConnectorBattle.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Agent\AbstractAgent.cs" />
    <Compile Include="Agent\AbstractMoveAgent.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DeepCore\DeepCore.Geometry\DeepCore.Geometry.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepCore\DeepCore.csproj" />
    <ProjectReference Include="..\DeepMetaGame.Data\DeepMetaGame.Data.csproj" />
  </ItemGroup>
</Project>