<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Version>1.2.15</Version>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DeepMeta.$(AssemblyName)</PackageId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DeepGame3D\DeepMetaGame.Data\DeepMetaGame.Data.csproj" />
    <ProjectReference Include="..\..\DeepGame3D\DeepMetaGame.Host\DeepMetaGame.Host.csproj" />
    <ProjectReference Include="..\..\DeepGame3D\DeepMetaGame.Slave\DeepMetaGame.Slave.csproj" />
    <ProjectReference Include="..\Gate.Client\Gate.Client.csproj" />
    <ProjectReference Include="..\Gate.Data\Gate.Data.csproj" />
  </ItemGroup>
</Project>