<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <RootNamespace>DeepCore</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Version>1.2.21</Version>
    <Deterministic>true</Deterministic>
    <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DeepMeta.$(AssemblyName)</PackageId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="EventSystem\**" />
    <EmbeddedResource Remove="EventSystem\**" />
    <None Remove="EventSystem\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="JsonHelper.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeepCore\DeepCore.csproj" />
  </ItemGroup>
</Project>