<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Version>1.2.16</Version>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DeepMeta.$(AssemblyName)</PackageId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Source'">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Protocol\**" />
    <EmbeddedResource Remove="Protocol\**" />
    <None Remove="Protocol\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeepCore.Voxel\DeepCore.Voxel.csproj" />
    <ProjectReference Include="..\DeepMetaGame.Data\DeepMetaGame.Data.csproj" />
    <ProjectReference Include="..\DeepMetaGame.Host\DeepMetaGame.Host.csproj" />
    <ProjectReference Include="..\Gate.Data\Gate.Data.csproj" />
    <ProjectReference Include="..\Gate.Server\Gate.Server.csproj" />
  </ItemGroup>
</Project>