<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net9.0-windows;net10.0-windows</TargetFrameworks>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.2.22</Version>
		<Deterministic>true</Deterministic>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
		<Configurations>Debug;Release;Source</Configurations>
	</PropertyGroup>
	<PropertyGroup>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>DeepMeta.$(AssemblyName)</PackageId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'!='Source'">
		<Reference Include="DeepGameEditor3D.Main">
			<HintPath>..\.outputs\net9.0-windows\DeepGameEditor3D.AI.dll</HintPath>
		</Reference>
		<Reference Include="DeepGameEditor3D.Main">
			<HintPath>..\.outputs\net9.0-windows\DeepGameEditor3D.Main.dll</HintPath>
		</Reference>
		<Reference Include="DeepGameEditor3D.MMO">
			<HintPath>..\.outputs\net9.0-windows\DeepGameEditor3D.MMO.dll</HintPath>
		</Reference>
		<Reference Include="DeepGameEditor3D.MMOServer">
			<HintPath>..\.outputs\net9.0-windows\DeepGameEditor3D.MMOServer.dll</HintPath>
		</Reference>
		<Reference Include="DeepGameEditor3D.Plugin3D">
			<HintPath>..\.outputs\net9.0-windows\DeepGameEditor3D.Plugin3D.dll</HintPath>
		</Reference>
		<Reference Include="DeepGameEditor3D.Unity3D">
			<HintPath>..\.outputs\net9.0-windows\DeepGameEditor3D.Unity3D.dll</HintPath>
		</Reference>
	</ItemGroup>


	<ItemGroup Condition="'$(Configuration)'=='Source'">
		<ProjectReference Include="..\..\DeepEditorMain\DeepGameEditor3D.Main\DeepGameEditor3D.Main.csproj" />
		<ProjectReference Include="..\..\DeepEditorMain\DeepGameEditor3D.MMO\DeepGameEditor3D.MMO.csproj" />
		<ProjectReference Include="..\..\DeepEditorMain\DeepGameEditor3D.MMOServer\DeepGameEditor3D.MMOServer.csproj" />
		<ProjectReference Include="..\..\DeepEditorMain\DeepGameEditor3D.Plugin3D\DeepGameEditor3D.Plugin3D.csproj" />
		<ProjectReference Include="..\..\DeepEditorMain\DeepGameEditor3D.Unity3D\DeepGameEditor3D.Unity3D.csproj" />
	</ItemGroup>

</Project>